"""
This type stub file was generated by pyright.
"""

import dagster as dg
import sqlalchemy
from typing import Generator
from contextlib import contextmanager

class PostGISResource(dg.ConfigurableResource):
    host: str
    port: str
    user: str
    password: str
    db: str
    _engine: sqlalchemy.engine.Engine = ...
    def setup_for_execution(self, context: dg.InitResourceContext) -> None: ...
    @contextmanager
    def connect(self) -> Generator[sqlalchemy.engine.Connection, None, None]: ...
